// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/NodeHeartBeat.proto

package org.poc.cache.server.proto;

public final class NodeHeartBeatOuterClass {
  private NodeHeartBeatOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NodeHeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.poc.cache.server.proto.NodeHeartBeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string heartBeatSource = 1;</code>
     * @return The heartBeatSource.
     */
    java.lang.String getHeartBeatSource();
    /**
     * <code>string heartBeatSource = 1;</code>
     * @return The bytes for heartBeatSource.
     */
    com.google.protobuf.ByteString
        getHeartBeatSourceBytes();

    /**
     * <pre>
     * List of live nodes
     * </pre>
     *
     * <code>repeated string liveNodes = 2;</code>
     * @return A list containing the liveNodes.
     */
    java.util.List<java.lang.String>
        getLiveNodesList();
    /**
     * <pre>
     * List of live nodes
     * </pre>
     *
     * <code>repeated string liveNodes = 2;</code>
     * @return The count of liveNodes.
     */
    int getLiveNodesCount();
    /**
     * <pre>
     * List of live nodes
     * </pre>
     *
     * <code>repeated string liveNodes = 2;</code>
     * @param index The index of the element to return.
     * @return The liveNodes at the given index.
     */
    java.lang.String getLiveNodes(int index);
    /**
     * <pre>
     * List of live nodes
     * </pre>
     *
     * <code>repeated string liveNodes = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the liveNodes at the given index.
     */
    com.google.protobuf.ByteString
        getLiveNodesBytes(int index);

    /**
     * <code>int32 heartBeatSequence = 3;</code>
     * @return The heartBeatSequence.
     */
    int getHeartBeatSequence();

    /**
     * <code>int64 heartBeatStartTime = 4;</code>
     * @return The heartBeatStartTime.
     */
    long getHeartBeatStartTime();
  }
  /**
   * Protobuf type {@code org.poc.cache.server.proto.NodeHeartBeat}
   */
  public static final class NodeHeartBeat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.poc.cache.server.proto.NodeHeartBeat)
      NodeHeartBeatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NodeHeartBeat.newBuilder() to construct.
    private NodeHeartBeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NodeHeartBeat() {
      heartBeatSource_ = "";
      liveNodes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NodeHeartBeat();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.poc.cache.server.proto.NodeHeartBeatOuterClass.internal_static_org_poc_cache_server_proto_NodeHeartBeat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.poc.cache.server.proto.NodeHeartBeatOuterClass.internal_static_org_poc_cache_server_proto_NodeHeartBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat.class, org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat.Builder.class);
    }

    public static final int HEARTBEATSOURCE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object heartBeatSource_ = "";
    /**
     * <code>string heartBeatSource = 1;</code>
     * @return The heartBeatSource.
     */
    @java.lang.Override
    public java.lang.String getHeartBeatSource() {
      java.lang.Object ref = heartBeatSource_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        heartBeatSource_ = s;
        return s;
      }
    }
    /**
     * <code>string heartBeatSource = 1;</code>
     * @return The bytes for heartBeatSource.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHeartBeatSourceBytes() {
      java.lang.Object ref = heartBeatSource_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        heartBeatSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LIVENODES_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList liveNodes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <pre>
     * List of live nodes
     * </pre>
     *
     * <code>repeated string liveNodes = 2;</code>
     * @return A list containing the liveNodes.
     */
    public com.google.protobuf.ProtocolStringList
        getLiveNodesList() {
      return liveNodes_;
    }
    /**
     * <pre>
     * List of live nodes
     * </pre>
     *
     * <code>repeated string liveNodes = 2;</code>
     * @return The count of liveNodes.
     */
    public int getLiveNodesCount() {
      return liveNodes_.size();
    }
    /**
     * <pre>
     * List of live nodes
     * </pre>
     *
     * <code>repeated string liveNodes = 2;</code>
     * @param index The index of the element to return.
     * @return The liveNodes at the given index.
     */
    public java.lang.String getLiveNodes(int index) {
      return liveNodes_.get(index);
    }
    /**
     * <pre>
     * List of live nodes
     * </pre>
     *
     * <code>repeated string liveNodes = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the liveNodes at the given index.
     */
    public com.google.protobuf.ByteString
        getLiveNodesBytes(int index) {
      return liveNodes_.getByteString(index);
    }

    public static final int HEARTBEATSEQUENCE_FIELD_NUMBER = 3;
    private int heartBeatSequence_ = 0;
    /**
     * <code>int32 heartBeatSequence = 3;</code>
     * @return The heartBeatSequence.
     */
    @java.lang.Override
    public int getHeartBeatSequence() {
      return heartBeatSequence_;
    }

    public static final int HEARTBEATSTARTTIME_FIELD_NUMBER = 4;
    private long heartBeatStartTime_ = 0L;
    /**
     * <code>int64 heartBeatStartTime = 4;</code>
     * @return The heartBeatStartTime.
     */
    @java.lang.Override
    public long getHeartBeatStartTime() {
      return heartBeatStartTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(heartBeatSource_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, heartBeatSource_);
      }
      for (int i = 0; i < liveNodes_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, liveNodes_.getRaw(i));
      }
      if (heartBeatSequence_ != 0) {
        output.writeInt32(3, heartBeatSequence_);
      }
      if (heartBeatStartTime_ != 0L) {
        output.writeInt64(4, heartBeatStartTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(heartBeatSource_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, heartBeatSource_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < liveNodes_.size(); i++) {
          dataSize += computeStringSizeNoTag(liveNodes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getLiveNodesList().size();
      }
      if (heartBeatSequence_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, heartBeatSequence_);
      }
      if (heartBeatStartTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, heartBeatStartTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat)) {
        return super.equals(obj);
      }
      org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat other = (org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat) obj;

      if (!getHeartBeatSource()
          .equals(other.getHeartBeatSource())) return false;
      if (!getLiveNodesList()
          .equals(other.getLiveNodesList())) return false;
      if (getHeartBeatSequence()
          != other.getHeartBeatSequence()) return false;
      if (getHeartBeatStartTime()
          != other.getHeartBeatStartTime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HEARTBEATSOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getHeartBeatSource().hashCode();
      if (getLiveNodesCount() > 0) {
        hash = (37 * hash) + LIVENODES_FIELD_NUMBER;
        hash = (53 * hash) + getLiveNodesList().hashCode();
      }
      hash = (37 * hash) + HEARTBEATSEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + getHeartBeatSequence();
      hash = (37 * hash) + HEARTBEATSTARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHeartBeatStartTime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.poc.cache.server.proto.NodeHeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.poc.cache.server.proto.NodeHeartBeat)
        org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.poc.cache.server.proto.NodeHeartBeatOuterClass.internal_static_org_poc_cache_server_proto_NodeHeartBeat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.poc.cache.server.proto.NodeHeartBeatOuterClass.internal_static_org_poc_cache_server_proto_NodeHeartBeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat.class, org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat.Builder.class);
      }

      // Construct using org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        heartBeatSource_ = "";
        liveNodes_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        heartBeatSequence_ = 0;
        heartBeatStartTime_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.poc.cache.server.proto.NodeHeartBeatOuterClass.internal_static_org_poc_cache_server_proto_NodeHeartBeat_descriptor;
      }

      @java.lang.Override
      public org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat getDefaultInstanceForType() {
        return org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat.getDefaultInstance();
      }

      @java.lang.Override
      public org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat build() {
        org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat buildPartial() {
        org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat result = new org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.heartBeatSource_ = heartBeatSource_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          liveNodes_.makeImmutable();
          result.liveNodes_ = liveNodes_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.heartBeatSequence_ = heartBeatSequence_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.heartBeatStartTime_ = heartBeatStartTime_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat) {
          return mergeFrom((org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat other) {
        if (other == org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat.getDefaultInstance()) return this;
        if (!other.getHeartBeatSource().isEmpty()) {
          heartBeatSource_ = other.heartBeatSource_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.liveNodes_.isEmpty()) {
          if (liveNodes_.isEmpty()) {
            liveNodes_ = other.liveNodes_;
            bitField0_ |= 0x00000002;
          } else {
            ensureLiveNodesIsMutable();
            liveNodes_.addAll(other.liveNodes_);
          }
          onChanged();
        }
        if (other.getHeartBeatSequence() != 0) {
          setHeartBeatSequence(other.getHeartBeatSequence());
        }
        if (other.getHeartBeatStartTime() != 0L) {
          setHeartBeatStartTime(other.getHeartBeatStartTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                heartBeatSource_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureLiveNodesIsMutable();
                liveNodes_.add(s);
                break;
              } // case 18
              case 24: {
                heartBeatSequence_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                heartBeatStartTime_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object heartBeatSource_ = "";
      /**
       * <code>string heartBeatSource = 1;</code>
       * @return The heartBeatSource.
       */
      public java.lang.String getHeartBeatSource() {
        java.lang.Object ref = heartBeatSource_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          heartBeatSource_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string heartBeatSource = 1;</code>
       * @return The bytes for heartBeatSource.
       */
      public com.google.protobuf.ByteString
          getHeartBeatSourceBytes() {
        java.lang.Object ref = heartBeatSource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          heartBeatSource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string heartBeatSource = 1;</code>
       * @param value The heartBeatSource to set.
       * @return This builder for chaining.
       */
      public Builder setHeartBeatSource(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        heartBeatSource_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string heartBeatSource = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeartBeatSource() {
        heartBeatSource_ = getDefaultInstance().getHeartBeatSource();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string heartBeatSource = 1;</code>
       * @param value The bytes for heartBeatSource to set.
       * @return This builder for chaining.
       */
      public Builder setHeartBeatSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        heartBeatSource_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList liveNodes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureLiveNodesIsMutable() {
        if (!liveNodes_.isModifiable()) {
          liveNodes_ = new com.google.protobuf.LazyStringArrayList(liveNodes_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <pre>
       * List of live nodes
       * </pre>
       *
       * <code>repeated string liveNodes = 2;</code>
       * @return A list containing the liveNodes.
       */
      public com.google.protobuf.ProtocolStringList
          getLiveNodesList() {
        liveNodes_.makeImmutable();
        return liveNodes_;
      }
      /**
       * <pre>
       * List of live nodes
       * </pre>
       *
       * <code>repeated string liveNodes = 2;</code>
       * @return The count of liveNodes.
       */
      public int getLiveNodesCount() {
        return liveNodes_.size();
      }
      /**
       * <pre>
       * List of live nodes
       * </pre>
       *
       * <code>repeated string liveNodes = 2;</code>
       * @param index The index of the element to return.
       * @return The liveNodes at the given index.
       */
      public java.lang.String getLiveNodes(int index) {
        return liveNodes_.get(index);
      }
      /**
       * <pre>
       * List of live nodes
       * </pre>
       *
       * <code>repeated string liveNodes = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the liveNodes at the given index.
       */
      public com.google.protobuf.ByteString
          getLiveNodesBytes(int index) {
        return liveNodes_.getByteString(index);
      }
      /**
       * <pre>
       * List of live nodes
       * </pre>
       *
       * <code>repeated string liveNodes = 2;</code>
       * @param index The index to set the value at.
       * @param value The liveNodes to set.
       * @return This builder for chaining.
       */
      public Builder setLiveNodes(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureLiveNodesIsMutable();
        liveNodes_.set(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of live nodes
       * </pre>
       *
       * <code>repeated string liveNodes = 2;</code>
       * @param value The liveNodes to add.
       * @return This builder for chaining.
       */
      public Builder addLiveNodes(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureLiveNodesIsMutable();
        liveNodes_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of live nodes
       * </pre>
       *
       * <code>repeated string liveNodes = 2;</code>
       * @param values The liveNodes to add.
       * @return This builder for chaining.
       */
      public Builder addAllLiveNodes(
          java.lang.Iterable<java.lang.String> values) {
        ensureLiveNodesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, liveNodes_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of live nodes
       * </pre>
       *
       * <code>repeated string liveNodes = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLiveNodes() {
        liveNodes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of live nodes
       * </pre>
       *
       * <code>repeated string liveNodes = 2;</code>
       * @param value The bytes of the liveNodes to add.
       * @return This builder for chaining.
       */
      public Builder addLiveNodesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureLiveNodesIsMutable();
        liveNodes_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int heartBeatSequence_ ;
      /**
       * <code>int32 heartBeatSequence = 3;</code>
       * @return The heartBeatSequence.
       */
      @java.lang.Override
      public int getHeartBeatSequence() {
        return heartBeatSequence_;
      }
      /**
       * <code>int32 heartBeatSequence = 3;</code>
       * @param value The heartBeatSequence to set.
       * @return This builder for chaining.
       */
      public Builder setHeartBeatSequence(int value) {

        heartBeatSequence_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 heartBeatSequence = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeartBeatSequence() {
        bitField0_ = (bitField0_ & ~0x00000004);
        heartBeatSequence_ = 0;
        onChanged();
        return this;
      }

      private long heartBeatStartTime_ ;
      /**
       * <code>int64 heartBeatStartTime = 4;</code>
       * @return The heartBeatStartTime.
       */
      @java.lang.Override
      public long getHeartBeatStartTime() {
        return heartBeatStartTime_;
      }
      /**
       * <code>int64 heartBeatStartTime = 4;</code>
       * @param value The heartBeatStartTime to set.
       * @return This builder for chaining.
       */
      public Builder setHeartBeatStartTime(long value) {

        heartBeatStartTime_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 heartBeatStartTime = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeartBeatStartTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        heartBeatStartTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.poc.cache.server.proto.NodeHeartBeat)
    }

    // @@protoc_insertion_point(class_scope:org.poc.cache.server.proto.NodeHeartBeat)
    private static final org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat();
    }

    public static org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NodeHeartBeat>
        PARSER = new com.google.protobuf.AbstractParser<NodeHeartBeat>() {
      @java.lang.Override
      public NodeHeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NodeHeartBeat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NodeHeartBeat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.poc.cache.server.proto.NodeHeartBeatOuterClass.NodeHeartBeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_poc_cache_server_proto_NodeHeartBeat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_poc_cache_server_proto_NodeHeartBeat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"src/main/proto/NodeHeartBeat.proto\022\032or" +
      "g.poc.cache.server.proto\"r\n\rNodeHeartBea" +
      "t\022\027\n\017heartBeatSource\030\001 \001(\t\022\021\n\tliveNodes\030" +
      "\002 \003(\t\022\031\n\021heartBeatSequence\030\003 \001(\005\022\032\n\022hear" +
      "tBeatStartTime\030\004 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_poc_cache_server_proto_NodeHeartBeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_poc_cache_server_proto_NodeHeartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_poc_cache_server_proto_NodeHeartBeat_descriptor,
        new java.lang.String[] { "HeartBeatSource", "LiveNodes", "HeartBeatSequence", "HeartBeatStartTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
