// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/OperationResponse.proto

package org.poc.cache.server.proto;

public final class OperationResponseOuterClass {
  private OperationResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OperationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.poc.cache.server.proto.OperationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.poc.cache.server.proto.OperationRequestType operationRequestType = 1;</code>
     * @return The enum numeric value on the wire for operationRequestType.
     */
    int getOperationRequestTypeValue();
    /**
     * <code>.org.poc.cache.server.proto.OperationRequestType operationRequestType = 1;</code>
     * @return The operationRequestType.
     */
    org.poc.cache.server.proto.OperationRequestTypeOuterClass.OperationRequestType getOperationRequestType();

    /**
     * <code>int32 storageName = 2;</code>
     * @return The storageName.
     */
    int getStorageName();

    /**
     * <code>optional string key = 3;</code>
     * @return Whether the key field is set.
     */
    boolean hasKey();
    /**
     * <code>optional string key = 3;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>optional string key = 3;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>optional bytes response = 4;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>optional bytes response = 4;</code>
     * @return The response.
     */
    com.google.protobuf.ByteString getResponse();

    /**
     * <code>optional bool boolResponse = 5;</code>
     * @return Whether the boolResponse field is set.
     */
    boolean hasBoolResponse();
    /**
     * <code>optional bool boolResponse = 5;</code>
     * @return The boolResponse.
     */
    boolean getBoolResponse();

    /**
     * <code>string requestId = 6;</code>
     * @return The requestId.
     */
    java.lang.String getRequestId();
    /**
     * <code>string requestId = 6;</code>
     * @return The bytes for requestId.
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();
  }
  /**
   * Protobuf type {@code org.poc.cache.server.proto.OperationResponse}
   */
  public static final class OperationResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.poc.cache.server.proto.OperationResponse)
      OperationResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OperationResponse.newBuilder() to construct.
    private OperationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OperationResponse() {
      operationRequestType_ = 0;
      key_ = "";
      response_ = com.google.protobuf.ByteString.EMPTY;
      requestId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OperationResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.poc.cache.server.proto.OperationResponseOuterClass.internal_static_org_poc_cache_server_proto_OperationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.poc.cache.server.proto.OperationResponseOuterClass.internal_static_org_poc_cache_server_proto_OperationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse.class, org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse.Builder.class);
    }

    private int bitField0_;
    public static final int OPERATIONREQUESTTYPE_FIELD_NUMBER = 1;
    private int operationRequestType_ = 0;
    /**
     * <code>.org.poc.cache.server.proto.OperationRequestType operationRequestType = 1;</code>
     * @return The enum numeric value on the wire for operationRequestType.
     */
    @java.lang.Override public int getOperationRequestTypeValue() {
      return operationRequestType_;
    }
    /**
     * <code>.org.poc.cache.server.proto.OperationRequestType operationRequestType = 1;</code>
     * @return The operationRequestType.
     */
    @java.lang.Override public org.poc.cache.server.proto.OperationRequestTypeOuterClass.OperationRequestType getOperationRequestType() {
      org.poc.cache.server.proto.OperationRequestTypeOuterClass.OperationRequestType result = org.poc.cache.server.proto.OperationRequestTypeOuterClass.OperationRequestType.forNumber(operationRequestType_);
      return result == null ? org.poc.cache.server.proto.OperationRequestTypeOuterClass.OperationRequestType.UNRECOGNIZED : result;
    }

    public static final int STORAGENAME_FIELD_NUMBER = 2;
    private int storageName_ = 0;
    /**
     * <code>int32 storageName = 2;</code>
     * @return The storageName.
     */
    @java.lang.Override
    public int getStorageName() {
      return storageName_;
    }

    public static final int KEY_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object key_ = "";
    /**
     * <code>optional string key = 3;</code>
     * @return Whether the key field is set.
     */
    @java.lang.Override
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string key = 3;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>optional string key = 3;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString response_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes response = 4;</code>
     * @return Whether the response field is set.
     */
    @java.lang.Override
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes response = 4;</code>
     * @return The response.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getResponse() {
      return response_;
    }

    public static final int BOOLRESPONSE_FIELD_NUMBER = 5;
    private boolean boolResponse_ = false;
    /**
     * <code>optional bool boolResponse = 5;</code>
     * @return Whether the boolResponse field is set.
     */
    @java.lang.Override
    public boolean hasBoolResponse() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bool boolResponse = 5;</code>
     * @return The boolResponse.
     */
    @java.lang.Override
    public boolean getBoolResponse() {
      return boolResponse_;
    }

    public static final int REQUESTID_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object requestId_ = "";
    /**
     * <code>string requestId = 6;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <code>string requestId = 6;</code>
     * @return The bytes for requestId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (operationRequestType_ != org.poc.cache.server.proto.OperationRequestTypeOuterClass.OperationRequestType.FETCH.getNumber()) {
        output.writeEnum(1, operationRequestType_);
      }
      if (storageName_ != 0) {
        output.writeInt32(2, storageName_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, key_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(4, response_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBool(5, boolResponse_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, requestId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (operationRequestType_ != org.poc.cache.server.proto.OperationRequestTypeOuterClass.OperationRequestType.FETCH.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, operationRequestType_);
      }
      if (storageName_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, storageName_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, key_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, response_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, boolResponse_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, requestId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse)) {
        return super.equals(obj);
      }
      org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse other = (org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse) obj;

      if (operationRequestType_ != other.operationRequestType_) return false;
      if (getStorageName()
          != other.getStorageName()) return false;
      if (hasKey() != other.hasKey()) return false;
      if (hasKey()) {
        if (!getKey()
            .equals(other.getKey())) return false;
      }
      if (hasResponse() != other.hasResponse()) return false;
      if (hasResponse()) {
        if (!getResponse()
            .equals(other.getResponse())) return false;
      }
      if (hasBoolResponse() != other.hasBoolResponse()) return false;
      if (hasBoolResponse()) {
        if (getBoolResponse()
            != other.getBoolResponse()) return false;
      }
      if (!getRequestId()
          .equals(other.getRequestId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPERATIONREQUESTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + operationRequestType_;
      hash = (37 * hash) + STORAGENAME_FIELD_NUMBER;
      hash = (53 * hash) + getStorageName();
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
      }
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      if (hasBoolResponse()) {
        hash = (37 * hash) + BOOLRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getBoolResponse());
      }
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.poc.cache.server.proto.OperationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.poc.cache.server.proto.OperationResponse)
        org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.poc.cache.server.proto.OperationResponseOuterClass.internal_static_org_poc_cache_server_proto_OperationResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.poc.cache.server.proto.OperationResponseOuterClass.internal_static_org_poc_cache_server_proto_OperationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse.class, org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse.Builder.class);
      }

      // Construct using org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        operationRequestType_ = 0;
        storageName_ = 0;
        key_ = "";
        response_ = com.google.protobuf.ByteString.EMPTY;
        boolResponse_ = false;
        requestId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.poc.cache.server.proto.OperationResponseOuterClass.internal_static_org_poc_cache_server_proto_OperationResponse_descriptor;
      }

      @java.lang.Override
      public org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse getDefaultInstanceForType() {
        return org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse build() {
        org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse buildPartial() {
        org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse result = new org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.operationRequestType_ = operationRequestType_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.storageName_ = storageName_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.key_ = key_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.response_ = response_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.boolResponse_ = boolResponse_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.requestId_ = requestId_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse) {
          return mergeFrom((org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse other) {
        if (other == org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse.getDefaultInstance()) return this;
        if (other.operationRequestType_ != 0) {
          setOperationRequestTypeValue(other.getOperationRequestTypeValue());
        }
        if (other.getStorageName() != 0) {
          setStorageName(other.getStorageName());
        }
        if (other.hasKey()) {
          key_ = other.key_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasResponse()) {
          setResponse(other.getResponse());
        }
        if (other.hasBoolResponse()) {
          setBoolResponse(other.getBoolResponse());
        }
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                operationRequestType_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                storageName_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                key_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                response_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                boolResponse_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                requestId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int operationRequestType_ = 0;
      /**
       * <code>.org.poc.cache.server.proto.OperationRequestType operationRequestType = 1;</code>
       * @return The enum numeric value on the wire for operationRequestType.
       */
      @java.lang.Override public int getOperationRequestTypeValue() {
        return operationRequestType_;
      }
      /**
       * <code>.org.poc.cache.server.proto.OperationRequestType operationRequestType = 1;</code>
       * @param value The enum numeric value on the wire for operationRequestType to set.
       * @return This builder for chaining.
       */
      public Builder setOperationRequestTypeValue(int value) {
        operationRequestType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.org.poc.cache.server.proto.OperationRequestType operationRequestType = 1;</code>
       * @return The operationRequestType.
       */
      @java.lang.Override
      public org.poc.cache.server.proto.OperationRequestTypeOuterClass.OperationRequestType getOperationRequestType() {
        org.poc.cache.server.proto.OperationRequestTypeOuterClass.OperationRequestType result = org.poc.cache.server.proto.OperationRequestTypeOuterClass.OperationRequestType.forNumber(operationRequestType_);
        return result == null ? org.poc.cache.server.proto.OperationRequestTypeOuterClass.OperationRequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.poc.cache.server.proto.OperationRequestType operationRequestType = 1;</code>
       * @param value The operationRequestType to set.
       * @return This builder for chaining.
       */
      public Builder setOperationRequestType(org.poc.cache.server.proto.OperationRequestTypeOuterClass.OperationRequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        operationRequestType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.poc.cache.server.proto.OperationRequestType operationRequestType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperationRequestType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        operationRequestType_ = 0;
        onChanged();
        return this;
      }

      private int storageName_ ;
      /**
       * <code>int32 storageName = 2;</code>
       * @return The storageName.
       */
      @java.lang.Override
      public int getStorageName() {
        return storageName_;
      }
      /**
       * <code>int32 storageName = 2;</code>
       * @param value The storageName to set.
       * @return This builder for chaining.
       */
      public Builder setStorageName(int value) {

        storageName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 storageName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStorageName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        storageName_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>optional string key = 3;</code>
       * @return Whether the key field is set.
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string key = 3;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string key = 3;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 3;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        key_ = getDefaultInstance().getKey();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 3;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        key_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString response_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes response = 4;</code>
       * @return Whether the response field is set.
       */
      @java.lang.Override
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bytes response = 4;</code>
       * @return The response.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getResponse() {
        return response_;
      }
      /**
       * <code>optional bytes response = 4;</code>
       * @param value The response to set.
       * @return This builder for chaining.
       */
      public Builder setResponse(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        response_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes response = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000008);
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }

      private boolean boolResponse_ ;
      /**
       * <code>optional bool boolResponse = 5;</code>
       * @return Whether the boolResponse field is set.
       */
      @java.lang.Override
      public boolean hasBoolResponse() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional bool boolResponse = 5;</code>
       * @return The boolResponse.
       */
      @java.lang.Override
      public boolean getBoolResponse() {
        return boolResponse_;
      }
      /**
       * <code>optional bool boolResponse = 5;</code>
       * @param value The boolResponse to set.
       * @return This builder for chaining.
       */
      public Builder setBoolResponse(boolean value) {

        boolResponse_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool boolResponse = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBoolResponse() {
        bitField0_ = (bitField0_ & ~0x00000010);
        boolResponse_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object requestId_ = "";
      /**
       * <code>string requestId = 6;</code>
       * @return The requestId.
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestId = 6;</code>
       * @return The bytes for requestId.
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestId = 6;</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        requestId_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string requestId = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        requestId_ = getDefaultInstance().getRequestId();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string requestId = 6;</code>
       * @param value The bytes for requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        requestId_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.poc.cache.server.proto.OperationResponse)
    }

    // @@protoc_insertion_point(class_scope:org.poc.cache.server.proto.OperationResponse)
    private static final org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse();
    }

    public static org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OperationResponse>
        PARSER = new com.google.protobuf.AbstractParser<OperationResponse>() {
      @java.lang.Override
      public OperationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OperationResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OperationResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.poc.cache.server.proto.OperationResponseOuterClass.OperationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_poc_cache_server_proto_OperationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_poc_cache_server_proto_OperationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&src/main/proto/OperationResponse.proto" +
      "\022\032org.poc.cache.server.proto\032)src/main/p" +
      "roto/OperationRequestType.proto\"\365\001\n\021Oper" +
      "ationResponse\022N\n\024operationRequestType\030\001 " +
      "\001(\01620.org.poc.cache.server.proto.Operati" +
      "onRequestType\022\023\n\013storageName\030\002 \001(\005\022\020\n\003ke" +
      "y\030\003 \001(\tH\000\210\001\001\022\025\n\010response\030\004 \001(\014H\001\210\001\001\022\031\n\014b" +
      "oolResponse\030\005 \001(\010H\002\210\001\001\022\021\n\trequestId\030\006 \001(" +
      "\tB\006\n\004_keyB\013\n\t_responseB\017\n\r_boolResponseb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.poc.cache.server.proto.OperationRequestTypeOuterClass.getDescriptor(),
        });
    internal_static_org_poc_cache_server_proto_OperationResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_poc_cache_server_proto_OperationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_poc_cache_server_proto_OperationResponse_descriptor,
        new java.lang.String[] { "OperationRequestType", "StorageName", "Key", "Response", "BoolResponse", "RequestId", "Key", "Response", "BoolResponse", });
    org.poc.cache.server.proto.OperationRequestTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
