// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/StorageNodeInfo.proto

package org.poc.cache.server.proto;

public final class StorageNodeInfoOuterClass {
  private StorageNodeInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StorageNodeInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.poc.cache.server.proto.StorageNodeInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * address of the node from where this message originated
     * </pre>
     *
     * <code>string nodeAddress = 1;</code>
     * @return The nodeAddress.
     */
    java.lang.String getNodeAddress();
    /**
     * <pre>
     * address of the node from where this message originated
     * </pre>
     *
     * <code>string nodeAddress = 1;</code>
     * @return The bytes for nodeAddress.
     */
    com.google.protobuf.ByteString
        getNodeAddressBytes();

    /**
     * <pre>
     * Unix EPOC of how long this node has been up
     * </pre>
     *
     * <code>int64 nodeUptimeUTC = 2;</code>
     * @return The nodeUptimeUTC.
     */
    long getNodeUptimeUTC();

    /**
     * <pre>
     * An increasing sequence incrementing when a new message is sent - resets to 0 on restart of the node
     * </pre>
     *
     * <code>int32 sequenceNumber = 3;</code>
     * @return The sequenceNumber.
     */
    int getSequenceNumber();

    /**
     * <pre>
     * Position on the consistent hashing ring space generated using Murmur hash -- hash space = 1024
     * </pre>
     *
     * <code>int32 indexPosition = 4;</code>
     * @return The indexPosition.
     */
    int getIndexPosition();
  }
  /**
   * Protobuf type {@code org.poc.cache.server.proto.StorageNodeInfo}
   */
  public static final class StorageNodeInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.poc.cache.server.proto.StorageNodeInfo)
      StorageNodeInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StorageNodeInfo.newBuilder() to construct.
    private StorageNodeInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StorageNodeInfo() {
      nodeAddress_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StorageNodeInfo();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.poc.cache.server.proto.StorageNodeInfoOuterClass.internal_static_org_poc_cache_server_proto_StorageNodeInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.poc.cache.server.proto.StorageNodeInfoOuterClass.internal_static_org_poc_cache_server_proto_StorageNodeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo.class, org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo.Builder.class);
    }

    public static final int NODEADDRESS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nodeAddress_ = "";
    /**
     * <pre>
     * address of the node from where this message originated
     * </pre>
     *
     * <code>string nodeAddress = 1;</code>
     * @return The nodeAddress.
     */
    @java.lang.Override
    public java.lang.String getNodeAddress() {
      java.lang.Object ref = nodeAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeAddress_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * address of the node from where this message originated
     * </pre>
     *
     * <code>string nodeAddress = 1;</code>
     * @return The bytes for nodeAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeAddressBytes() {
      java.lang.Object ref = nodeAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODEUPTIMEUTC_FIELD_NUMBER = 2;
    private long nodeUptimeUTC_ = 0L;
    /**
     * <pre>
     * Unix EPOC of how long this node has been up
     * </pre>
     *
     * <code>int64 nodeUptimeUTC = 2;</code>
     * @return The nodeUptimeUTC.
     */
    @java.lang.Override
    public long getNodeUptimeUTC() {
      return nodeUptimeUTC_;
    }

    public static final int SEQUENCENUMBER_FIELD_NUMBER = 3;
    private int sequenceNumber_ = 0;
    /**
     * <pre>
     * An increasing sequence incrementing when a new message is sent - resets to 0 on restart of the node
     * </pre>
     *
     * <code>int32 sequenceNumber = 3;</code>
     * @return The sequenceNumber.
     */
    @java.lang.Override
    public int getSequenceNumber() {
      return sequenceNumber_;
    }

    public static final int INDEXPOSITION_FIELD_NUMBER = 4;
    private int indexPosition_ = 0;
    /**
     * <pre>
     * Position on the consistent hashing ring space generated using Murmur hash -- hash space = 1024
     * </pre>
     *
     * <code>int32 indexPosition = 4;</code>
     * @return The indexPosition.
     */
    @java.lang.Override
    public int getIndexPosition() {
      return indexPosition_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeAddress_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeAddress_);
      }
      if (nodeUptimeUTC_ != 0L) {
        output.writeInt64(2, nodeUptimeUTC_);
      }
      if (sequenceNumber_ != 0) {
        output.writeInt32(3, sequenceNumber_);
      }
      if (indexPosition_ != 0) {
        output.writeInt32(4, indexPosition_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeAddress_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nodeAddress_);
      }
      if (nodeUptimeUTC_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, nodeUptimeUTC_);
      }
      if (sequenceNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sequenceNumber_);
      }
      if (indexPosition_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, indexPosition_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo)) {
        return super.equals(obj);
      }
      org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo other = (org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo) obj;

      if (!getNodeAddress()
          .equals(other.getNodeAddress())) return false;
      if (getNodeUptimeUTC()
          != other.getNodeUptimeUTC()) return false;
      if (getSequenceNumber()
          != other.getSequenceNumber()) return false;
      if (getIndexPosition()
          != other.getIndexPosition()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODEADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getNodeAddress().hashCode();
      hash = (37 * hash) + NODEUPTIMEUTC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNodeUptimeUTC());
      hash = (37 * hash) + SEQUENCENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getSequenceNumber();
      hash = (37 * hash) + INDEXPOSITION_FIELD_NUMBER;
      hash = (53 * hash) + getIndexPosition();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.poc.cache.server.proto.StorageNodeInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.poc.cache.server.proto.StorageNodeInfo)
        org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.poc.cache.server.proto.StorageNodeInfoOuterClass.internal_static_org_poc_cache_server_proto_StorageNodeInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.poc.cache.server.proto.StorageNodeInfoOuterClass.internal_static_org_poc_cache_server_proto_StorageNodeInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo.class, org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo.Builder.class);
      }

      // Construct using org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nodeAddress_ = "";
        nodeUptimeUTC_ = 0L;
        sequenceNumber_ = 0;
        indexPosition_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.poc.cache.server.proto.StorageNodeInfoOuterClass.internal_static_org_poc_cache_server_proto_StorageNodeInfo_descriptor;
      }

      @java.lang.Override
      public org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo getDefaultInstanceForType() {
        return org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo.getDefaultInstance();
      }

      @java.lang.Override
      public org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo build() {
        org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo buildPartial() {
        org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo result = new org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nodeAddress_ = nodeAddress_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.nodeUptimeUTC_ = nodeUptimeUTC_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sequenceNumber_ = sequenceNumber_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.indexPosition_ = indexPosition_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo) {
          return mergeFrom((org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo other) {
        if (other == org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo.getDefaultInstance()) return this;
        if (!other.getNodeAddress().isEmpty()) {
          nodeAddress_ = other.nodeAddress_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getNodeUptimeUTC() != 0L) {
          setNodeUptimeUTC(other.getNodeUptimeUTC());
        }
        if (other.getSequenceNumber() != 0) {
          setSequenceNumber(other.getSequenceNumber());
        }
        if (other.getIndexPosition() != 0) {
          setIndexPosition(other.getIndexPosition());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nodeAddress_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                nodeUptimeUTC_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                sequenceNumber_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                indexPosition_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object nodeAddress_ = "";
      /**
       * <pre>
       * address of the node from where this message originated
       * </pre>
       *
       * <code>string nodeAddress = 1;</code>
       * @return The nodeAddress.
       */
      public java.lang.String getNodeAddress() {
        java.lang.Object ref = nodeAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * address of the node from where this message originated
       * </pre>
       *
       * <code>string nodeAddress = 1;</code>
       * @return The bytes for nodeAddress.
       */
      public com.google.protobuf.ByteString
          getNodeAddressBytes() {
        java.lang.Object ref = nodeAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * address of the node from where this message originated
       * </pre>
       *
       * <code>string nodeAddress = 1;</code>
       * @param value The nodeAddress to set.
       * @return This builder for chaining.
       */
      public Builder setNodeAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nodeAddress_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * address of the node from where this message originated
       * </pre>
       *
       * <code>string nodeAddress = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeAddress() {
        nodeAddress_ = getDefaultInstance().getNodeAddress();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * address of the node from where this message originated
       * </pre>
       *
       * <code>string nodeAddress = 1;</code>
       * @param value The bytes for nodeAddress to set.
       * @return This builder for chaining.
       */
      public Builder setNodeAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nodeAddress_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private long nodeUptimeUTC_ ;
      /**
       * <pre>
       * Unix EPOC of how long this node has been up
       * </pre>
       *
       * <code>int64 nodeUptimeUTC = 2;</code>
       * @return The nodeUptimeUTC.
       */
      @java.lang.Override
      public long getNodeUptimeUTC() {
        return nodeUptimeUTC_;
      }
      /**
       * <pre>
       * Unix EPOC of how long this node has been up
       * </pre>
       *
       * <code>int64 nodeUptimeUTC = 2;</code>
       * @param value The nodeUptimeUTC to set.
       * @return This builder for chaining.
       */
      public Builder setNodeUptimeUTC(long value) {

        nodeUptimeUTC_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unix EPOC of how long this node has been up
       * </pre>
       *
       * <code>int64 nodeUptimeUTC = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeUptimeUTC() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nodeUptimeUTC_ = 0L;
        onChanged();
        return this;
      }

      private int sequenceNumber_ ;
      /**
       * <pre>
       * An increasing sequence incrementing when a new message is sent - resets to 0 on restart of the node
       * </pre>
       *
       * <code>int32 sequenceNumber = 3;</code>
       * @return The sequenceNumber.
       */
      @java.lang.Override
      public int getSequenceNumber() {
        return sequenceNumber_;
      }
      /**
       * <pre>
       * An increasing sequence incrementing when a new message is sent - resets to 0 on restart of the node
       * </pre>
       *
       * <code>int32 sequenceNumber = 3;</code>
       * @param value The sequenceNumber to set.
       * @return This builder for chaining.
       */
      public Builder setSequenceNumber(int value) {

        sequenceNumber_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * An increasing sequence incrementing when a new message is sent - resets to 0 on restart of the node
       * </pre>
       *
       * <code>int32 sequenceNumber = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSequenceNumber() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sequenceNumber_ = 0;
        onChanged();
        return this;
      }

      private int indexPosition_ ;
      /**
       * <pre>
       * Position on the consistent hashing ring space generated using Murmur hash -- hash space = 1024
       * </pre>
       *
       * <code>int32 indexPosition = 4;</code>
       * @return The indexPosition.
       */
      @java.lang.Override
      public int getIndexPosition() {
        return indexPosition_;
      }
      /**
       * <pre>
       * Position on the consistent hashing ring space generated using Murmur hash -- hash space = 1024
       * </pre>
       *
       * <code>int32 indexPosition = 4;</code>
       * @param value The indexPosition to set.
       * @return This builder for chaining.
       */
      public Builder setIndexPosition(int value) {

        indexPosition_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Position on the consistent hashing ring space generated using Murmur hash -- hash space = 1024
       * </pre>
       *
       * <code>int32 indexPosition = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndexPosition() {
        bitField0_ = (bitField0_ & ~0x00000008);
        indexPosition_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.poc.cache.server.proto.StorageNodeInfo)
    }

    // @@protoc_insertion_point(class_scope:org.poc.cache.server.proto.StorageNodeInfo)
    private static final org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo();
    }

    public static org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StorageNodeInfo>
        PARSER = new com.google.protobuf.AbstractParser<StorageNodeInfo>() {
      @java.lang.Override
      public StorageNodeInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StorageNodeInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StorageNodeInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.poc.cache.server.proto.StorageNodeInfoOuterClass.StorageNodeInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_poc_cache_server_proto_StorageNodeInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_poc_cache_server_proto_StorageNodeInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$src/main/proto/StorageNodeInfo.proto\022\032" +
      "org.poc.cache.server.proto\"l\n\017StorageNod" +
      "eInfo\022\023\n\013nodeAddress\030\001 \001(\t\022\025\n\rnodeUptime" +
      "UTC\030\002 \001(\003\022\026\n\016sequenceNumber\030\003 \001(\005\022\025\n\rind" +
      "exPosition\030\004 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_poc_cache_server_proto_StorageNodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_poc_cache_server_proto_StorageNodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_poc_cache_server_proto_StorageNodeInfo_descriptor,
        new java.lang.String[] { "NodeAddress", "NodeUptimeUTC", "SequenceNumber", "IndexPosition", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
