// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/StorageKeyLocation.proto

package org.poc.cache.server.proto;

public final class StorageKeyLocationOuterClass {
  private StorageKeyLocationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StorageKeyLocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.poc.cache.server.proto.StorageKeyLocation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * All keys are stored in Storage as Byte Arrays.However to make local caching of key easier - each object will have a StringiField Key which will be hashed
     * </pre>
     *
     * <code>string key = 1;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <pre>
     * All keys are stored in Storage as Byte Arrays.However to make local caching of key easier - each object will have a StringiField Key which will be hashed
     * </pre>
     *
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <pre>
     * Node that currently holds this key
     * </pre>
     *
     * <code>string node = 2;</code>
     * @return The node.
     */
    java.lang.String getNode();
    /**
     * <pre>
     * Node that currently holds this key
     * </pre>
     *
     * <code>string node = 2;</code>
     * @return The bytes for node.
     */
    com.google.protobuf.ByteString
        getNodeBytes();
  }
  /**
   * Protobuf type {@code org.poc.cache.server.proto.StorageKeyLocation}
   */
  public static final class StorageKeyLocation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.poc.cache.server.proto.StorageKeyLocation)
      StorageKeyLocationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StorageKeyLocation.newBuilder() to construct.
    private StorageKeyLocation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StorageKeyLocation() {
      key_ = "";
      node_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StorageKeyLocation();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.poc.cache.server.proto.StorageKeyLocationOuterClass.internal_static_org_poc_cache_server_proto_StorageKeyLocation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.poc.cache.server.proto.StorageKeyLocationOuterClass.internal_static_org_poc_cache_server_proto_StorageKeyLocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation.class, org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object key_ = "";
    /**
     * <pre>
     * All keys are stored in Storage as Byte Arrays.However to make local caching of key easier - each object will have a StringiField Key which will be hashed
     * </pre>
     *
     * <code>string key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * All keys are stored in Storage as Byte Arrays.However to make local caching of key easier - each object will have a StringiField Key which will be hashed
     * </pre>
     *
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object node_ = "";
    /**
     * <pre>
     * Node that currently holds this key
     * </pre>
     *
     * <code>string node = 2;</code>
     * @return The node.
     */
    @java.lang.Override
    public java.lang.String getNode() {
      java.lang.Object ref = node_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        node_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Node that currently holds this key
     * </pre>
     *
     * <code>string node = 2;</code>
     * @return The bytes for node.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeBytes() {
      java.lang.Object ref = node_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        node_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(node_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, node_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(node_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, node_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation)) {
        return super.equals(obj);
      }
      org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation other = (org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (!getNode()
          .equals(other.getNode())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + NODE_FIELD_NUMBER;
      hash = (53 * hash) + getNode().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.poc.cache.server.proto.StorageKeyLocation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.poc.cache.server.proto.StorageKeyLocation)
        org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.poc.cache.server.proto.StorageKeyLocationOuterClass.internal_static_org_poc_cache_server_proto_StorageKeyLocation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.poc.cache.server.proto.StorageKeyLocationOuterClass.internal_static_org_poc_cache_server_proto_StorageKeyLocation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation.class, org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation.Builder.class);
      }

      // Construct using org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        key_ = "";
        node_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.poc.cache.server.proto.StorageKeyLocationOuterClass.internal_static_org_poc_cache_server_proto_StorageKeyLocation_descriptor;
      }

      @java.lang.Override
      public org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation getDefaultInstanceForType() {
        return org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation.getDefaultInstance();
      }

      @java.lang.Override
      public org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation build() {
        org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation buildPartial() {
        org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation result = new org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.key_ = key_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.node_ = node_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation) {
          return mergeFrom((org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation other) {
        if (other == org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getNode().isEmpty()) {
          node_ = other.node_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                key_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                node_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <pre>
       * All keys are stored in Storage as Byte Arrays.However to make local caching of key easier - each object will have a StringiField Key which will be hashed
       * </pre>
       *
       * <code>string key = 1;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * All keys are stored in Storage as Byte Arrays.However to make local caching of key easier - each object will have a StringiField Key which will be hashed
       * </pre>
       *
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * All keys are stored in Storage as Byte Arrays.However to make local caching of key easier - each object will have a StringiField Key which will be hashed
       * </pre>
       *
       * <code>string key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * All keys are stored in Storage as Byte Arrays.However to make local caching of key easier - each object will have a StringiField Key which will be hashed
       * </pre>
       *
       * <code>string key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        key_ = getDefaultInstance().getKey();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * All keys are stored in Storage as Byte Arrays.However to make local caching of key easier - each object will have a StringiField Key which will be hashed
       * </pre>
       *
       * <code>string key = 1;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object node_ = "";
      /**
       * <pre>
       * Node that currently holds this key
       * </pre>
       *
       * <code>string node = 2;</code>
       * @return The node.
       */
      public java.lang.String getNode() {
        java.lang.Object ref = node_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          node_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Node that currently holds this key
       * </pre>
       *
       * <code>string node = 2;</code>
       * @return The bytes for node.
       */
      public com.google.protobuf.ByteString
          getNodeBytes() {
        java.lang.Object ref = node_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          node_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Node that currently holds this key
       * </pre>
       *
       * <code>string node = 2;</code>
       * @param value The node to set.
       * @return This builder for chaining.
       */
      public Builder setNode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        node_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node that currently holds this key
       * </pre>
       *
       * <code>string node = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNode() {
        node_ = getDefaultInstance().getNode();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node that currently holds this key
       * </pre>
       *
       * <code>string node = 2;</code>
       * @param value The bytes for node to set.
       * @return This builder for chaining.
       */
      public Builder setNodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        node_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.poc.cache.server.proto.StorageKeyLocation)
    }

    // @@protoc_insertion_point(class_scope:org.poc.cache.server.proto.StorageKeyLocation)
    private static final org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation();
    }

    public static org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StorageKeyLocation>
        PARSER = new com.google.protobuf.AbstractParser<StorageKeyLocation>() {
      @java.lang.Override
      public StorageKeyLocation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StorageKeyLocation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StorageKeyLocation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.poc.cache.server.proto.StorageKeyLocationOuterClass.StorageKeyLocation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_poc_cache_server_proto_StorageKeyLocation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_poc_cache_server_proto_StorageKeyLocation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'src/main/proto/StorageKeyLocation.prot" +
      "o\022\032org.poc.cache.server.proto\"/\n\022Storage" +
      "KeyLocation\022\013\n\003key\030\001 \001(\t\022\014\n\004node\030\002 \001(\tb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_poc_cache_server_proto_StorageKeyLocation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_poc_cache_server_proto_StorageKeyLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_poc_cache_server_proto_StorageKeyLocation_descriptor,
        new java.lang.String[] { "Key", "Node", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
